### PR TITLE
Add docker installation

### PR DESCRIPTION
**Pull request by stefpiatek**
From https://github.com/UCLH-Foundry/the-running-skeleton/issues/26 it sounded like we should install docker desktop, but let me know if this isn't the case

Running docker for the first time gets WSL to download ubuntu image and create a default user. Also had to edit WSL script to wait for the process to finish as was failing during build

Checked:

- [x] Docker engine is started when running docker desktop
- [x] Can pull and run [hello-world](https://hub.docker.com/_/hello-world) image from docker desktop UI

### CODE REVIEW

**Review by dram1964 — APPROVED** [review]
Given the docker dependancy on WSL, should we merge the two scripts into one?

**Comment by stefpiatek** [comment]
not a bad shout, also have had more fun since trying to get both wsl and docker to run when installed by packer so will close for now. I'll reopen once I've got something working

**Comment by stefpiatek** [comment]
Cant quite work out where to run the [enabling of nested virtualisation](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization) step, but haven't been able to get this to instantiate a new vm with `D2s v3` instance without some manual steps on the VM. I've found two ways to get docker working, neither of them are seamless sadly

## Users run the install script themselves?

Running the install powershell script and restarting, Docker desktop does then work as expected. This may be more simple than trying to fix the installation?

## Fix packer installation

WSL install by packer doesn't seem to work as expected, which can be checked by
```powershell
 wsl --status
```

This suggests updating wsl using:
```powershell
wsl --update
```

I _think_ Docker requires the user to be added to the docker group in windows:
```powershell
net localgroup docker-users <user> /add
```

After doing this, restart the VM. Then install ubuntu distribution for wsl

```powershell
wsl --install -d Ubuntu
```



I restarted the VM again, and then ran docker desktop which did work

**Comment by dram1964** [comment]
Suspect that the 'install from script option' wouldn't work, as TRE users would probably be blocked from accessing the sites where the installer files are located. The 'fix packer installation' steps might need to be carried out in the [init scripts](templates/workspace_services/guacamole/user_resources/guacamole-azure-windowsvm/terraform/vm_config.ps1) for the individual VMs - that is, they'd probably need to be incorporated into the TRE User Resource.

**Comment by dram1964** [comment]
> Suspect that the 'install from script option' wouldn't work, as TRE users would probably be blocked from accessing the sites where the installer files are located. 

However, we could pre-download the installer file, and then alter the script to use that. Then we could add instructions to the User Docs on how to install Docker?

**Comment by stefpiatek** [comment]
closing as defined as out of scope for now, but can use this script as a basis later on

**Pull request closed without merging**
